### ISSUE TITLE
Using Manticoresearch-java client in an Android App

### ISSUE THREAD

**Issue by AmirDotDev0** [manticoresoftware/manticoresearch-java#11]
Hello, I want to implement search functionality on my app using Manticoresearch but I'm not sure which is the best way, I'm wondering if the Java client can be implemented in an Android app or should I use the JavaScript client in my nodejs API and get the search results from my rest API?

**Comment by sanikolaev** [comment]
> if the Java client can be implemented in an Android app

Even if your Android app can't utilize the Java client, you have the option to directly use the Manticore HTTP JSON API, it shouldn't be much more difficult. Besides, you're already experienced with using a REST API in your app.

**Comment by AmirDotDev0** [comment]
Good to know, Thanks for the clarification.
