### ISSUE TITLE
has integration  spring boot demo code??

### ISSUE THREAD

**Issue by startjava** [manticoresoftware/manticoresearch-java#13]
has integration spring boot demo code??
please give me a few url.

**Comment by Nick-S-2018** [comment]
So far, we don't fully support Spring Boot.  The related issue's been discussed [here](https://github.com/manticoresoftware/manticoresearch-java/issues/9).
In general,  we use the  [OpenApiGenerator](https://github.com/OpenAPITools/openapi-generator) tool for generating out clients. Now it has a generator for [SpringBoot](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/spring.md) too, so if you are interested in this, you could generate the client by yourself and made a request for us to add it as a new Manticore client.  You can look [here](https://github.com/manticoresoftware/openapi) for the examples of how our other clients are implemented.

**Comment by FriskKiddo** [comment]
hi, have a plan to publish your newest client to solve it ?

**Comment by Nick-S-2018** [comment]
Hi,
This issue has already been solved, and the Java client can work with SpringBoot now.  You can use the demo code from Readme as an example.
