### ISSUE TITLE
Generate a Java Spring Boot client

### ISSUE THREAD

**Issue by Nick-S-2018** [manticoresoftware/manticoresearch-java#16]
To provide better integration of Manticore and Spring Boot, we need to generate a separate client using the corresponding templates from OpenApI Generator.

**Comment by ayaankhan98** [comment]
Any updates on this?

**Comment by sanikolaev** [comment]
Unfortunately not. PRs are welcome!

**Comment by Nick-S-2018** [comment]
It's not necessary any more as Spring Boot is now supported in the Java client:  https://github.com/manticoresoftware/manticoresearch-java/releases/tag/5.0.0
