### ISSUE TITLE
How to add AttrFilters in SearchRequest

### ISSUE THREAD

**Issue by FriskKiddo** [manticoresoftware/manticoresearch-java#21]
i want to implement the sql: select * from table where a = 'aaa' and b >= 12 and b <= 15

java code:
SearchRequest searchRequest = new SearchRequest();
searchRequest.index("table");
EqualsFilter equalsFilter = new EqualsFilter();
equalsFilter.setField("a");
equalsFilter.setValue("aaa");
RangeFilter rangeFilter = new RangeFilter();
rangeFilter.setField("b");
rangeFilter.setGte(new BigDecimal("12"));
rangeFilter.setLte(new BigDecimal("15"));
searchRequest.setAttrFilter(equalsFilter);
// then how to add rangeFilter

**Comment by FriskKiddo** [comment]
UtilApi can do it

**Comment by Nick-S-2018** [comment]
Hi,
Currently, Manticore does not allow using multiple attribute filters in one request. If you need to combine different filtering conditions, you should use the 'bool' query instead: https://manual.manticoresearch.com/dev/Searching/Filters#bool-query

**Comment by sanikolaev** [comment]
Closing as resolved. Feel free to reopen in case you believe there's an issue in the library. Otherwise, please consider using the [Discussions](https://github.com/manticoresoftware/manticoresearch-java/discussions) instead.
