### ISSUE TITLE
ApiClient's AuthMap is never used

### ISSUE THREAD

**Issue by statista-oss** [manticoresoftware/manticoresearch-java#3]
https://github.com/manticoresoftware/manticoresearch-java/blob/5bc58a066d0bca3ad27ddfa1e0ef7d49a5d14cd3/src/main/java/com/manticoresearch/client/ApiClient.java#L120

Currently it appears that any authMap that submitted to initialize ApiClient is ignored and an empty HashMap is always initialised and used instead. This prevents the library being used for any project that requires authentication. We would like to use HttpBasicAuth to interact with our json search endpoint, but currently no valid authentication is ever found.

Sorry, this is unformatted. Github was not reproducing the code block. Here is how we have initialised the SearchApi:

```
public class SearchApiFactory {
    public static SearchApiFactory getApi(ObjectMapper objectMapper, String server, String username, String password) {
        ApiClient apiClient = getClientWithBasicAuth();
        apiClient.setBasePath(server);
        apiClient.setUsername(username); // fails here because no Http Basic Authentication can be found
        apiClient.setPassword(password);
        return new SearchApi(apiClient);
    }

    private static ApiClient getClientWithBasicAuth() {
        Map<String, Authentication> authenticationMap = new HashMap<>();
        HttpBasicAuth basicAuth = new HttpBasicAuth();
        authenticationMap.put("httpBasicAuth", basicAuth);

        return new ApiClient(authenticationMap);
    }
}
```

**Comment by sanikolaev** [comment]
> We would like to use HttpBasicAuth to interact with our json search endpoint

Manticore doesn't yet support http basic authentication. By "json search endpoint" do you mean you have smth else in between the client and the Manticore Search which supports the authentication which you'd like to use?

**Comment by statista-oss** [comment]
Hi Sergey, thank you. Yes, we have implemented Basic Auth on the endpoint in front of the Manticore Search. I thought I could use the ApiClient to negotiate the authorization, but it's not a problem if that is not the the case. Thank you for the feedback. Given the references in the code to Basic Auth, I take it it is planned feature?

**Comment by statista-oss** [comment]
In the meantime I will close the issue.

**Comment by sanikolaev** [comment]
> Given the references in the code to Basic Auth, I take it it is planned feature?

It's not in the nearest plans, but yes, eventually we'll need to add authentication out of the box.
