### ISSUE TITLE
Version compatibility with 4.2.1

### ISSUE THREAD

**Issue by pavelnemirovsky** [manticoresoftware/manticoresearch-java#5]
Can you please confirm that SQL API is compatible with 4.2.1-220217, we tried to use it and it seems it is no longer working and return following response: 
```
{"error": "query missing"}
```

**Comment by pavelnemirovsky** [comment]
Can you please confirm that SQL API is compatible with 4.2.1-220217, we tried to use it and it seems it is no longer working and return following response: 
```
{"error": "query missing"}
```

**Comment by sanikolaev** [comment]
I confirm that **the development** version of this cilent (i.e. the latest commit in this repository) should be compatible with the development version (4.2.1) of Manticore Search. If it's not please provide more details on the issue.
