### ISSUE TITLE
Maven Repo is missing manticore client version 3.2.0

### ISSUE THREAD

**Issue by pavelnemirovsky** [manticoresoftware/manticoresearch-java#7]
Guys please advise, what client version I should use together with Manticore 5.x? 
![image](https://user-images.githubusercontent.com/19474975/171621768-d13d3470-4c65-4783-8797-003ba643413a.png)

**Comment by Nick-S-2018** [comment]
Hi,
We've updated the repo with the new version 3.2.0,  you can check it here 
https://oss.sonatype.org/#nexus-search;quick~manticoresearch
